apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-mem-cpu-pod
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    resources:
      limits:
        memory: "1Gi"
        cpu: "750m"
      requests:
        memory: "500Mi"
        cpu: "500m"
    ports:
     - containerPort: 22
