apiVersion: v1
kind: Pod
metadata:
  name: hammadpodredis
  labels:
    role: redis-role
    app: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    volumeMounts:
      - name: redis-storage
        mountPath: /data/redis
    resources:
      limits:
        memory: "200Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "0.5"
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1", "--cpus", "1"]
    ports:
     - containerPort: 6379
  volumes:
    - name: redis-storage
      emptyDir: {}
